### PR TITLE
Flux progression reworked

### PR DESCRIPTION
**Pull request by ilightwas**
- Removed loose rock flux recipes
- Buffed flux output for quern recipes
- Added nautilus and hollow shells flux recipes
- Changed some IE recipes to use treated sticks

### CODE REVIEW

**Comment by pietro-lopes** [comment]
This is a core mechanic of TerraFirmaCraft.
If this change is approved, we need to update TFC Book entry and quests to be in sync with changes.

**Comment by ilightwas** [comment]
> This is a core mechanic of TerraFirmaCraft. If this change is approved, we need to update TFC Book entry and quests to be in sync with changes.

Yeah, I didn't see a way to change the book. About the quests,  you are right, I completely forgot, but in my playthrough I'm still stuck at the glitched rock anvil one. If there's no way to change the entry on the book I think the tooltip I added is enough.

**Comment by pietro-lopes** [comment]
Those changes are trivial, but I wonder what is the point of making flux harder than original TFC.
With these changes, you are forcing players to find Ocean earlier than they need to find Salt Water, and you still can make salt water with salt you find around the world (you can skip Ocean until you need to go to Nether)
The Borax option will be a nightmare, like Kaolinite/Graphite, even with hint stones.

**Comment by thevortex** [comment]
yeah i am not keen on making the early game even harder, lol i am good with adding means to process borax etc in mid game but i dont want to make flux nearly impossible in the early game if you get a bad spawn area, do we need to undo a previous commit?

**Pull request closed without merging**
